/* Copyright 2025 The OpenXLA Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

// Systematic accuracy tests for XLA intrinsics against golden baselines.
//
// These tests measure the ULP error of each intrinsic implementation across
// ~200 domain-spanning reference points (generated by mpmath at 50-digit
// precision). The goals are:
//
// 1. Pin the current accuracy profile of each intrinsic.
// 2. Detect regressions when implementations change.
// 3. Provide side-by-side comparison data when migrating to Eigen-generated
//    intrinsics.
//
// Each test reports: max ULP error, mean ULP error, p99, and worst-case input.

#include <cmath>
#include <functional>
#include <memory>
#include <utility>

#include <gtest/gtest.h>
#include "llvm/IR/Function.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Verifier.h"
#include "xla/codegen/intrinsic/accuracy/accuracy_budget.h"
#include "xla/codegen/intrinsic/accuracy/accuracy_test_framework.h"
#include "xla/codegen/intrinsic/accuracy/golden_baselines.h"
#include "xla/codegen/intrinsic/erf.h"
#include "xla/codegen/intrinsic/exp.h"
#include "xla/codegen/intrinsic/intrinsic.h"
#include "xla/codegen/intrinsic/log1p.h"
#include "xla/codegen/intrinsic/rsqrt.h"
#include "xla/codegen/intrinsic/simple_jit_runner.h"
#include "xla/codegen/intrinsic/tanh.h"
#include "xla/xla_data.pb.h"

namespace xla::codegen::intrinsic::accuracy {
namespace {

using ::xla::codegen::intrinsic::JitRunner;

// Helper: create a JIT runner with a single intrinsic definition.
template <typename IntrinsicT>
JitRunner CreateRunner(Type type) {
  auto context = std::make_unique<llvm::LLVMContext>();
  auto module = std::make_unique<llvm::Module>("accuracy_test", *context);
  llvm::Function* fn =
      IntrinsicT::CreateDefinition(module.get(), type).value();
  fn->setLinkage(llvm::Function::ExternalLinkage);
  EXPECT_FALSE(llvm::verifyFunction(*fn));
  return JitRunner(std::move(module), std::move(context));
}

// =========================================================================
// Tanh
// =========================================================================

TEST(IntrinsicAccuracy, TanhF32) {
  Type type = Type::S(F32);
  JitRunner runner = CreateRunner<xla::codegen::intrinsics::Tanh>(type);
  auto* fn = runner.GetScalarFn<float(float)>(
      xla::codegen::intrinsics::Tanh::Name(type));

  auto report = TestAccuracyF32("tanh", kGoldenTanh,
                                std::function<float(float)>(fn));
  AssertWithinBudget(report, kTanhF32MaxUlp);
}

TEST(IntrinsicAccuracy, TanhF64) {
  Type type = Type::S(F64);
  JitRunner runner = CreateRunner<xla::codegen::intrinsics::Tanh>(type);
  auto* fn = runner.GetScalarFn<double(double)>(
      xla::codegen::intrinsics::Tanh::Name(type));

  auto report = TestAccuracyF64("tanh", kGoldenTanh,
                                std::function<double(double)>(fn));
  AssertWithinBudget(report, kTanhF64MaxUlp);
}

// Also test std::tanh to establish the platform's libm accuracy.
TEST(LibmBaseline, TanhF32) {
  auto report = TestAccuracyF32(
      "std::tanh", kGoldenTanh,
      std::function<float(float)>([](float x) { return std::tanh(x); }));
  LogReport(report);
  // Don't assert budget — this is informational.
}

TEST(LibmBaseline, TanhF64) {
  auto report = TestAccuracyF64(
      "std::tanh", kGoldenTanh,
      std::function<double(double)>([](double x) { return std::tanh(x); }));
  LogReport(report);
}

// =========================================================================
// Erf
// =========================================================================

TEST(IntrinsicAccuracy, ErfF32) {
  Type type = Type::S(F32);
  JitRunner runner = CreateRunner<xla::codegen::intrinsics::Erf>(type);
  auto* fn = runner.GetScalarFn<float(float)>(
      xla::codegen::intrinsics::Erf::Name(type));

  auto report = TestAccuracyF32("erf", kGoldenErf,
                                std::function<float(float)>(fn));
  AssertWithinBudget(report, kErfF32MaxUlp);
}

TEST(LibmBaseline, ErfF32) {
  auto report = TestAccuracyF32(
      "std::erf", kGoldenErf,
      std::function<float(float)>([](float x) { return std::erff(x); }));
  LogReport(report);
}

// =========================================================================
// Exp
// =========================================================================

TEST(IntrinsicAccuracy, ExpF64) {
  Type type = Type::S(F64);
  JitRunner runner = CreateRunner<xla::codegen::intrinsics::Exp>(type);
  auto* fn = runner.GetScalarFn<double(double)>(
      xla::codegen::intrinsics::Exp::Name(type));

  auto report = TestAccuracyF64("exp", kGoldenExp,
                                std::function<double(double)>(fn));
  AssertWithinBudget(report, kExpF64MaxUlp);
}

TEST(LibmBaseline, ExpF64) {
  auto report = TestAccuracyF64(
      "std::exp", kGoldenExp,
      std::function<double(double)>([](double x) { return std::exp(x); }));
  LogReport(report);
}

TEST(LibmBaseline, ExpF32) {
  auto report = TestAccuracyF32(
      "std::exp", kGoldenExp,
      std::function<float(float)>([](float x) { return std::expf(x); }));
  LogReport(report);
}

// =========================================================================
// Log1p
// =========================================================================

TEST(IntrinsicAccuracy, Log1pF32) {
  Type type = Type::S(F32);
  JitRunner runner = CreateRunner<xla::codegen::intrinsics::Log1p>(type);
  auto* fn = runner.GetScalarFn<float(float)>(
      xla::codegen::intrinsics::Log1p::Name(type));

  auto report = TestAccuracyF32("log1p", kGoldenLog1p,
                                std::function<float(float)>(fn));
  AssertWithinBudget(report, kLog1pF32MaxUlp);
}

TEST(IntrinsicAccuracy, Log1pF64) {
  Type type = Type::S(F64);
  JitRunner runner = CreateRunner<xla::codegen::intrinsics::Log1p>(type);
  auto* fn = runner.GetScalarFn<double(double)>(
      xla::codegen::intrinsics::Log1p::Name(type));

  auto report = TestAccuracyF64("log1p", kGoldenLog1p,
                                std::function<double(double)>(fn));
  AssertWithinBudget(report, kLog1pF64MaxUlp);
}

TEST(LibmBaseline, Log1pF32) {
  auto report = TestAccuracyF32(
      "std::log1p", kGoldenLog1p,
      std::function<float(float)>([](float x) { return std::log1pf(x); }));
  LogReport(report);
}

TEST(LibmBaseline, Log1pF64) {
  auto report = TestAccuracyF64(
      "std::log1p", kGoldenLog1p,
      std::function<double(double)>([](double x) { return std::log1p(x); }));
  LogReport(report);
}

// =========================================================================
// Rsqrt
// =========================================================================

TEST(IntrinsicAccuracy, RsqrtF32) {
  Type type = Type::S(F32);
  JitRunner runner =
      CreateRunner<xla::codegen::intrinsics::Rsqrt>(type);
  auto* fn = runner.GetScalarFn<float(float)>(
      xla::codegen::intrinsics::Rsqrt::Name(type));

  auto report = TestAccuracyF32("rsqrt", kGoldenRsqrt,
                                std::function<float(float)>(fn));
  AssertWithinBudget(report, kRsqrtF32MaxUlp);
}

TEST(IntrinsicAccuracy, RsqrtF64) {
  Type type = Type::S(F64);
  JitRunner runner =
      CreateRunner<xla::codegen::intrinsics::Rsqrt>(type);
  auto* fn = runner.GetScalarFn<double(double)>(
      xla::codegen::intrinsics::Rsqrt::Name(type));

  auto report = TestAccuracyF64("rsqrt", kGoldenRsqrt,
                                std::function<double(double)>(fn));
  AssertWithinBudget(report, kRsqrtF64MaxUlp);
}

TEST(LibmBaseline, RsqrtF32) {
  auto report = TestAccuracyF32(
      "1/std::sqrt", kGoldenRsqrt,
      std::function<float(float)>(
          [](float x) { return 1.0f / std::sqrtf(x); }));
  LogReport(report);
}

TEST(LibmBaseline, RsqrtF64) {
  auto report = TestAccuracyF64(
      "1/std::sqrt", kGoldenRsqrt,
      std::function<double(double)>(
          [](double x) { return 1.0 / std::sqrt(x); }));
  LogReport(report);
}

// =========================================================================
// Libm-only baselines for functions not yet implemented as intrinsics.
// These establish a baseline for when we add Eigen implementations.
// =========================================================================

TEST(LibmBaseline, SinF32) {
  auto report = TestAccuracyF32(
      "std::sin", kGoldenSin,
      std::function<float(float)>([](float x) { return std::sinf(x); }));
  LogReport(report);
}

TEST(LibmBaseline, SinF64) {
  auto report = TestAccuracyF64(
      "std::sin", kGoldenSin,
      std::function<double(double)>([](double x) { return std::sin(x); }));
  LogReport(report);
}

TEST(LibmBaseline, CosF32) {
  auto report = TestAccuracyF32(
      "std::cos", kGoldenCos,
      std::function<float(float)>([](float x) { return std::cosf(x); }));
  LogReport(report);
}

TEST(LibmBaseline, CosF64) {
  auto report = TestAccuracyF64(
      "std::cos", kGoldenCos,
      std::function<double(double)>([](double x) { return std::cos(x); }));
  LogReport(report);
}

TEST(LibmBaseline, LogF32) {
  auto report = TestAccuracyF32(
      "std::log", kGoldenLog,
      std::function<float(float)>([](float x) { return std::logf(x); }));
  LogReport(report);
}

TEST(LibmBaseline, LogF64) {
  auto report = TestAccuracyF64(
      "std::log", kGoldenLog,
      std::function<double(double)>([](double x) { return std::log(x); }));
  LogReport(report);
}

TEST(LibmBaseline, Expm1F32) {
  auto report = TestAccuracyF32(
      "std::expm1", kGoldenExpm1,
      std::function<float(float)>([](float x) { return std::expm1f(x); }));
  LogReport(report);
}

TEST(LibmBaseline, Expm1F64) {
  auto report = TestAccuracyF64(
      "std::expm1", kGoldenExpm1,
      std::function<double(double)>([](double x) { return std::expm1(x); }));
  LogReport(report);
}

}  // namespace
}  // namespace xla::codegen::intrinsic::accuracy
